/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreateStockArgs } from "./CreateStockArgs";
import { UpdateStockArgs } from "./UpdateStockArgs";
import { DeleteStockArgs } from "./DeleteStockArgs";
import { StockFindManyArgs } from "./StockFindManyArgs";
import { StockFindUniqueArgs } from "./StockFindUniqueArgs";
import { Stock } from "./Stock";
import { StockService } from "../stock.service";

@graphql.Resolver(() => Stock)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class StockResolverBase {
  constructor(
    protected readonly service: StockService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Stock",
    action: "read",
    possession: "any",
  })
  async _stocksMeta(
    @graphql.Args() args: StockFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Stock])
  @nestAccessControl.UseRoles({
    resource: "Stock",
    action: "read",
    possession: "any",
  })
  async stocks(@graphql.Args() args: StockFindManyArgs): Promise<Stock[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Stock, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Stock",
    action: "read",
    possession: "own",
  })
  async stock(
    @graphql.Args() args: StockFindUniqueArgs
  ): Promise<Stock | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Stock)
  @nestAccessControl.UseRoles({
    resource: "Stock",
    action: "create",
    possession: "any",
  })
  async createStock(@graphql.Args() args: CreateStockArgs): Promise<Stock> {
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Stock)
  @nestAccessControl.UseRoles({
    resource: "Stock",
    action: "update",
    possession: "any",
  })
  async updateStock(
    @graphql.Args() args: UpdateStockArgs
  ): Promise<Stock | null> {
    try {
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Stock)
  @nestAccessControl.UseRoles({
    resource: "Stock",
    action: "delete",
    possession: "any",
  })
  async deleteStock(
    @graphql.Args() args: DeleteStockArgs
  ): Promise<Stock | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
